a1_19.m
piandi/EngThermoDyn pull request #2
Opened 2019-04-30 03:43 UTC by HWLOU

2019-05-05 09:22 UTC, piandi requested changes

2019-05-05 09:22 UTC, piandi commented on a1_18.m
> +elta = 0.35;
change "elta" into "eta"

2019-05-05 09:22 UTC, piandi commented on a1_18.m
> +disp(sprintf('���ȼ�����Ϊ %.3f kJ \n', double(Qm)))
Use fprintf() due to disp(sprintf()) is out dated.

2019-05-05 09:22 UTC, piandi commented on a2_10.m
> +[P1,v1,P2,v2,deltau,q,c]=deal(x{:});
Directly assign the values into the variables.

2019-05-05 09:22 UTC, piandi commented on a2_18.m
> +[dE_CV]=solve(eq)
Declare the solving variable. It is risky to let Matlab guess what you want.

2019-05-08 12:18 UTC, HWLOU commented
Please send me students'chapter 3 homework.

2019-06-17 22:03 UTC, piandi commented
@HWLOU  在所有你写的代码前两行注释下你的姓名首字母缩写，例如% by LHW on 2019-5-4

2019-10-02 14:35 UTC, closed without merging